### PR TITLE
Fix for plugin load failures, mass tagger crash

### LINKED ISSUE #53: Crash when using Update From Tag function
Open puddletag, select some non-MP3 files and try to use the Update from Tag function with an ID3 tag: (the files I used for this are OGG format)

updatefromtag-crash (1)

Puddletag crashes with this exception:

```
Traceback (most recent call last):
  File "../puddletag/source/puddlestuff/actiondlg.py", line 364, in showexample
    val = apply_actions([self.func], audio, state, fields)
  File "../puddletag/source/puddlestuff/findfunc.py", line 623, in apply_actions
    temp = func.runFunction(val, audio, state, None, r_tags)
  File "../puddletag/source/puddlestuff/findfunc.py", line 873, in runFunction
    return func(**topass)
  File "../puddletag/source/puddlestuff/functions.py", line 1037, in update_from_tag
    tag = _update[tag]().link(r_tags.filepath)
  File "../puddletag/source/puddlestuff/audioinfo/id3.py", line 1002, in link
    tags, audio = self.load(filename, id3_filetype)
  File "../puddletag/source/puddlestuff/audioinfo/util.py", line 838, in load
    audio = filetype(filename)
  File "/usr/lib/python3.8/site-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "../puddletag/source/puddlestuff/audioinfo/id3.py", line 761, in load
    return super(ID3FileType, self).load(filename, ID3, **kwargs)
  File "/usr/lib/python3.8/site-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mutagen/id3/_file.py", line 423, in load
    self.info = self._Info(fileobj, offset)
  File "/usr/lib/python3.8/site-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mutagen/mp3/__init__.py", line 403, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
../puddletag/launch.bash: line 3: 25495 Aborted                 (core dumped) PYTHONPATH=source/ ./source/puddletag
```

I've fixed the crash in https://github.com/blueblots/puddletag/commit/8a1de3f195eb168046ee576ae4be6eb4674968b9, but it would be better if the function stopped immediately when it notices that there is no MP3 tags in the file and displayed a message to notify the user. Currently it just tries to continue doing`update_from_tag`, but only gets None values and empty dicts until it finishes.

This is a pdb trace of what happens when the `update_from_tag` function hits the mutagen error (with the fix applied so it does not core dump):

```
> ../puddletag/source/puddlestuff/functions.py(1045)update_from_tag()
-> return
(Pdb) next
--Return--
> ../puddletag/source/puddlestuff/functions.py(1045)update_from_tag()->None
-> return
(Pdb) next
--Return--
> ../puddletag/source/puddlestuff/findfunc.py(873)runFunction()->None
-> return func(**topass)
(Pdb) next
> ../puddletag/source/puddlestuff/findfunc.py(624)apply_actions()
-> if temp is None:
(Pdb) temp
(Pdb) next
> ../puddletag/source/puddlestuff/findfunc.py(625)apply_actions()
-> continue
(Pdb) l
620  
621             for field in fields:
622                 val = audio.get(field, '')
623                 temp = func.runFunction(val, audio, state, None, r_tags)
624                 if temp is None:
625  ->                 continue
626                 if isinstance(temp, str):
627                     ret[field] = temp
628                 elif hasattr(temp, 'items'):
629                     ret.update(temp)
630                     break
(Pdb) next
> ../puddletag/source/puddlestuff/findfunc.py(621)apply_actions()
-> for field in fields:
(Pdb) l
616                 fields = parse_field_list(func.tag, audio)
617             else:
618                 fields = ovr_fields[::]
619             ret = {}
620  
621  ->         for field in fields:
622                 val = audio.get(field, '')
623                 temp = func.runFunction(val, audio, state, None, r_tags)
624                 if temp is None:
625                     continue
626                 if isinstance(temp, str):
(Pdb) field
'just nothing to do with this'
(Pdb) fields
['just nothing to do with this']
(Pdb) next
> ../puddletag/source/puddlestuff/findfunc.py(643)apply_actions()
-> ret = dict([z for z in ret.items() if z[1] is not None])
(Pdb) l
638                         ret[field] = temp[0]
639                     else:
640                         ret[field] = temp
641                 else:
642                     ret[field] = temp[0]
643  ->         ret = dict([z for z in ret.items() if z[1] is not None])
644             if ret:
645                 [changed.add(z) for z in ret]
646                 audio.update(ret)
647         return dict([(z, audio[z]) for z in changed])
648  
(Pdb) ret
{}
(Pdb) next
> ../puddletag/source/puddlestuff/findfunc.py(644)apply_actions()
-> if ret:
(Pdb) ret
{}
(Pdb) next
> ../puddletag/source/puddlestuff/findfunc.py(614)apply_actions()
-> for func in actions:
(Pdb) ret
{}
(Pdb) func
<puddlestuff.findfunc.Function object at 0x7f0b7c03d580>
(Pdb) actions
[<puddlestuff.findfunc.Function object at 0x7f0b7c03d580>]
(Pdb) actions.function
*** AttributeError: 'list' object has no attribute 'function'
(Pdb) actions.info
*** AttributeError: 'list' object has no attribute 'info'
(Pdb) actions.doc
*** AttributeError: 'list' object has no attribute 'doc'
(Pdb) next
> ../puddletag/source/puddlestuff/findfunc.py(647)apply_actions()
-> return dict([(z, audio[z]) for z in changed])
(Pdb) l
642                     ret[field] = temp[0]
643             ret = dict([z for z in ret.items() if z[1] is not None])
644             if ret:
645                 [changed.add(z) for z in ret]
646                 audio.update(ret)
647  ->     return dict([(z, audio[z]) for z in changed])
648  
649  
650     def apply_macros(macros, audio, state, fields=None):
651         actions = []
652         for m in macros:
(Pdb) l
653             actions.extend(m.actions)
654  
655         if fields:
656             return apply_actions(actions, audio, state, fields)
657         else:
658             return apply_actions(actions, audio, state)
659  
660  
661     def runQuickAction(funcs, audio, state, tag):
662         """Same as runAction, except that all funcs are
663         applied not in the values stored but on audio[tag]."""
(Pdb) next
--Return--
> ../puddletag/source/puddlestuff/findfunc.py(647)apply_actions()->{}
-> return dict([(z, audio[z]) for z in changed])
(Pdb) z
*** NameError: name 'z' is not defined
(Pdb) changed
set()
(Pdb) next
> ../puddletag/source/puddlestuff/actiondlg.py(367)showexample()
-> if val is not None:
(Pdb) val
{}
(Pdb) next
> ../puddletag/source/puddlestuff/actiondlg.py(368)showexample()
-> self.updateExample.emit(val)
(Pdb) l
363                     state = {'__counter': '0', '__total_files': files}
364                     val = apply_actions([self.func], audio, state, fields)
365                 except findfunc.ParseError as e:
366                     val = '<b>%s</b>' % (e.message)
367                 if val is not None:
368  ->                 self.updateExample.emit(val)
369                 else:
370                     self.updateExample.emit(translate('Functions Dialog', '<b>No change</b>'))
371  
372         def _sanitize(self, ctype, value):
373             if ctype in ['combo', 'text']:
(Pdb) next
--Return--
> ../puddletag/source/puddlestuff/actiondlg.py(368)showexample()->None
-> self.updateExample.emit(val)
(Pdb) l
363                     state = {'__counter': '0', '__total_files': files}
364                     val = apply_actions([self.func], audio, state, fields)
365                 except findfunc.ParseError as e:
366                     val = '<b>%s</b>' % (e.message)
367                 if val is not None:
368  ->                 self.updateExample.emit(val)
369                 else:
370                     self.updateExample.emit(translate('Functions Dialog', '<b>No change</b>'))
371  
372         def _sanitize(self, ctype, value):
373             if ctype in ['combo', 'text']:
(Pdb) next
> ../puddletag/source/puddlestuff/actiondlg.py(404)setArguments()
-> for argument, control in zip(args, self.controls):
(Pdb) next
--Return--
> ../puddletag/source/puddlestuff/actiondlg.py(404)setArguments()->None
-> for argument, control in zip(args, self.controls):
(Pdb) next
--Return--
> ../puddletag/source/puddlestuff/actiondlg.py(335)loadSettings()->None
-> self.setArguments(fields, arguments)
(Pdb) next
> ../puddletag/source/puddlestuff/actiondlg.py(496)createWindow()
-> self.stackWidgets.update({index: widget})
(Pdb) next
> ../puddletag/source/puddlestuff/actiondlg.py(497)createWindow()
-> self.stack.addWidget(widget)
(Pdb) next
> ../puddletag/source/puddlestuff/actiondlg.py(498)createWindow()
-> widget.updateExample.connect(self.updateExample)
(Pdb) next
> ../puddletag/source/puddlestuff/actiondlg.py(499)createWindow()
-> self.stack.setCurrentWidget(self.stackWidgets[index])
(Pdb) next
> ../puddletag/source/puddlestuff/actiondlg.py(500)createWindow()
-> self.stackWidgets[index].showexample()
(Pdb) next
> ../puddletag/source/puddlestuff/functions.py(1045)update_from_tag()
-> return
(Pdb) next
--Return--
> ../puddletag/source/puddlestuff/functions.py(1045)update_from_tag()->None
-> return
(Pdb) next
--Return--

```

### LINKED ISSUE #55: Pressing 'search' in empty masstagging dialog causes crash
A fix for this is in https://github.com/sandrotosi/puddletag/pull/52

1. Open puddletag and open mass tagging panel
2. Click search without selecting a profile.

Puddletag crashes with the exception:

```
puddletag Version: 2.0.0
Locale: en_US
Traceback (most recent call last):
  File "../puddletag/source/puddlestuff/masstag/dialogs.py", line 589, in lookup
    self._start()
  File "../puddletag/source/puddlestuff/masstag/dialogs.py", line 625, in _start
    mtp.file_pattern)
AttributeError: 'NoneType' object has no attribute 'file_pattern'
```

### PR DESCRIPTION
**Pull request by blueblots**
Sorry about the file permissions in https://github.com/sandrotosi/puddletag/pull/52, that change was not intentional.

This includes fixes for most of the plugin crashes in #41: 

source/puddlestuff/plugins/dupe_fields/__init__.py
source/puddlestuff/plugins/extended_tags/__init__.py
source/puddlestuff/plugins/id3_tools/__init__.py
source/puddlestuff/plugins/modified_time/__init__.py
source/puddlestuff/plugins/save_tags/__init__.py

as well an issue with the mass tagging dialog crashing under certain circumstances as noted in https://github.com/sandrotosi/puddletag/issues/55 and https://github.com/sandrotosi/puddletag/issues/53:

source/puddlestuff/functions.py - fixes #53 
source/puddlestuff/masstag/dialogs.py - fixes #55 

Also removed an unnecessary 'u' from the front of a string in line 814 in source/puddlestuff/findfunc.py.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It seems there's still too much commits, including merge ones. IMO this makes the repo very dirty. Is it possible to squash them together into one?

**Comment by pedrobaeza** [comment]
And why changing relative imports to absolute ones? That shouldn't be the fix.

**Comment by blueblots** [comment]
the relative plugin imports were throwing these exceptions:

```
puddletag Version: 2.0.0
Locale: en_US


[2020-07-17 20:05:32,284]ERROR:Failed to load plugin: Extended Tags

Traceback (most recent call last):
  File "../puddletag/source/puddlestuff/pluginloader.py", line 70, in load_plugins
    module = __import__(plugin[MODULE_NAME])
  File "../puddletag/source/puddlestuff/plugins/extended_tags/__init__.py", line 4, in <module>
    from ...audioinfo import commontags
ValueError: attempted relative import beyond top-level package


[2020-07-17 20:05:32,285]ERROR:Failed to load plugin: Highlight duplicate fields.

Traceback (most recent call last):
  File "../puddletag/source/puddlestuff/pluginloader.py", line 70, in load_plugins
    module = __import__(plugin[MODULE_NAME])
  File "../puddletag/source/puddlestuff/plugins/dupe_fields/__init__.py", line 4, in <module>
    from .. import status, connect_control
ValueError: attempted relative import beyond top-level package


[2020-07-17 20:05:32,286]ERROR:Failed to load plugin: ID3 Tools.

Traceback (most recent call last):
  File "../puddletag/source/puddlestuff/pluginloader.py", line 70, in load_plugins
    module = __import__(plugin[MODULE_NAME])
  File "../puddletag/source/puddlestuff/plugins/id3_tools/__init__.py", line 6, in <module>
    from .. import connect_shortcut, status
ValueError: attempted relative import beyond top-level package
```

I tried different combos of relative import, but none of them were working except the absolute ones. hence the change.

**Comment by pedrobaeza** [comment]
But I would say that it's something with your installation, not on the source code itself. I'm using it without problems.

**Comment by blueblots** [comment]
the merge commits were to prevent conflicts with the upstream branch, I had to revert a few commits to fix the permissions issue. also i was under the impression that rebasing and similiar tactics that erase history are not prefered in public repos.

**Comment by blueblots** [comment]
@audiomuze seems to have the same issue: https://github.com/sandrotosi/puddletag/issues/41

**Comment by pedrobaeza** [comment]
This is not a public repo, but your branch, so you have to rebase your branch against `pyqt5+py3` one, and fix conflict that way. Merge conflicts solved by your merge commit are due to local changes you have done.

**Comment by pedrobaeza** [comment]
Please indicate in your bug reports how did you install the sources

**Comment by blueblots** [comment]
i cloned the source from this repo. with the neccessary dependencies installed, of course.

**Comment by pedrobaeza** [comment]
I did exactly the same, but you are not indicating how do you run it. I do:
```
PYTHONPATH=/.../puddletag/source /.../puddletag/source/puddletag
```

**Comment by sandrotosi** [comment]
> Sorry about the file permissions in #52, that change was not intentional.

that's alright, that's why we review PRs :)

> This includes fixes for most of the plugin crashes #41 as well an issue with the mass tagging dialog crashing under certain circumstances as noted in #55 and #53.

can you mark them as "Fix #nn" in the commit msg or the [body of the PR](https://github.blog/2013-05-14-closing-issues-via-pull-requests/) ?

> Also removed an unnecessary 'u' from the front of a string in findfunc.py.

yep that's good, unicode for all!

**Comment by blueblots** [comment]
I've rebased it now, is its current state more acceptable? i dont think i can get rid of the second commit without making a new pull request.

**Comment by blueblots** [comment]
About the plugins not loading, the way I launch puddletag is this:

#!/bin/bash

PYTHONPATH=source/ ./source/puddletag

in a shell script from the top of the repository. running this script immediately launches puddletag. i dont see why this would impact the imports though.

**Comment by sandrotosi** [comment]
@blueblots i imagine the plugins fail to load [here](https://github.com/sandrotosi/puddletag/blob/pyqt5%2Bpy3/source/puddlestuff/pluginloader.py#L66-L70) correct? maybe instead of using `__import__` we should do something as the [tag source loader does](https://github.com/sandrotosi/puddletag/blob/pyqt5%2Bpy3/source/puddlestuff/tagsources/__init__.py#L244-L249)? wanna give it a try? and then we'll go from there (most likely it will be cleaner in a new, pristine PR, but lets see if that approach works with plugins first

**Comment by elsabio** [comment]
Have you seen my comments on https://github.com/sandrotosi/puddletag/issues/41#?  I have started a solution based on             `module = import_module('.' + plugin[MODULE_NAME], package='puddlestuff.plugins')`, which works, but needs a little more work.

**Comment by sandrotosi** [comment]
> Have you seen my comments on #41? I have started a solution based on `module = import_module('.' + plugin[MODULE_NAME], package='puddlestuff.plugins')`, which works, but needs a little more work.

i see it now :) i commented on #58, once that's completed and merged, we can rebase this PR on top of that to fix the remaining issues

**Comment by sandrotosi** [comment]
@blueblots now that #58 is merged, i think you can rebase your work on top of it (ideally in a new pr, will probably make things a lot  clearer that way)

**Comment by blueblots** [comment]
ok will do.

**Comment by sandrotosi** [comment]
thanks @blueblots ! but maybe you should open a PR against https://github.com/puddletag/puddletag/tree/sandro-py3 -- Keith just merged this repo into that branch of the main project, and we're gonna cut a release from it soon.

I'll migrate this repo issues to that one soon

**Pull request closed without merging**
