### PR TITLE
[FIX] sorted: Use key instead of cmp

### LINKED ISSUE #15: `sorted` with old P2 argument `cmp` instead of `key`
There are several places where the `sorted` method is used using the old `cmp` argument. I have found for example when opening extended tags dialog.

I can provide a patch sorting this out, but I have seen that @sandrotosi has already touch a bit code involved in class compare in puddleobjects.py, so I don't want to mix the work.

### PR DESCRIPTION
**Pull request by pedrobaeza**
Fixes #15

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This might fix #4 as well.

**Comment by sandrotosi** [comment]
> This might fix #4 as well.

probably not: i think i fixed the traceback originally used to open #4, but then there are other issues downstream

**Comment by sandrotosi** [comment]
thanks for your contributions! did you notice anything else we should fix? PR away :)

**Comment by pedrobaeza** [comment]
I will continue checking and tell you back.

**Pull request merged**
