### PR TITLE
Fixed load m3u playlist exception

### PR DESCRIPTION
**Pull request by blueblots**
Original issue: https://github.com/sandrotosi/puddletag/issues/9

I removed the style changes from the commit as requested.

### CODE REVIEW

**Comment by blueblots** [comment]
I accidentally added another patch to this PR, do you want me to redo the request?

**Comment by sandrotosi** [comment]
> I accidentally added another patch to this PR, do you want me to redo the request?

naah, every fix is welcome!

**Comment by sandrotosi** [comment]
Due to other recent fixes for pyqt5 ports, I had to revert the playlist commit 3ced262e5aa1f9e280ccf9ef31ce2f8a7969c7bb (i kept the other one).

loading a playlist doesnt crash puddletag anymore, but doesnt load anything actually

**Comment by sandrotosi** [comment]
nvm, please disregard the comment of loading a playlist not working: it was a spurious file (without .mp3 extension) that caused the load to fail

**Pull request merged**
